2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_setup.py:_flush():80] Configure stats pid to 727396
2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_setup.py:_flush():80] Loading settings from /root/.config/wandb/settings
2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_setup.py:_flush():80] Loading settings from /workspace/auto-avsr/wandb/settings
2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_init.py:setup_run_log_directory():703] Logging user logs to ./wandb/run-20250709_204512-mi49oyls/logs/debug.log
2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to ./wandb/run-20250709_204512-mi49oyls/logs/debug-internal.log
2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_init.py:init():830] calling init triggers
2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-07-09 20:45:12,478 INFO    MainThread:727396 [wandb_init.py:init():871] starting backend
2025-07-09 20:45:12,684 INFO    MainThread:727396 [wandb_init.py:init():874] sending inform_init request
2025-07-09 20:45:12,688 INFO    MainThread:727396 [wandb_init.py:init():882] backend started and connected
2025-07-09 20:45:12,688 INFO    MainThread:727396 [wandb_init.py:init():953] updated telemetry
2025-07-09 20:45:12,691 INFO    MainThread:727396 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-09 20:45:13,477 INFO    MainThread:727396 [wandb_init.py:init():1029] starting run threads in backend
2025-07-09 20:45:13,481 WARNING MainThread:727396 [wandb_init.py:init():1610] [no run ID] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1606, in init
    return wi.init(run_settings, run_config, run_printer)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1074, in init
    run._on_start()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2482, in _on_start
    self._backend.interface.publish_python_packages(working_set())
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 347, in publish_python_packages
    for pkg in working_set:
  File "/opt/conda/lib/python3.10/site-packages/wandb/util.py", line 1938, in working_set
    yield InstalledDistribution(key=d.metadata["Name"], version=d.version)
  File "/opt/conda/lib/python3.10/importlib/metadata/__init__.py", line 605, in metadata
    self.read_text('METADATA')
  File "/opt/conda/lib/python3.10/importlib/metadata/__init__.py", line 927, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
  File "/opt/conda/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/opt/conda/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
  File "/opt/conda/lib/python3.10/codecs.py", line 309, in __init__
    def __init__(self, errors='strict'):
KeyboardInterrupt
2025-07-09 20:45:14,479 INFO    MsgRouterThr:727396 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
